version: "3.8"
services:
  mongodb:
    container_name: mongo-server
    image: mongo:5.0.3
    restart: always
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_CONTAINER_PORT
    volumes:
      - mongodb_database:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fetch-posts-network

  fetch-posts-api:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    container_name: fetch-posts-api
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_CONTAINER_PORT
    stdin_open: true
    tty: true
    networks:
      - fetch-posts-network
    volumes:
      - .:/src/app

volumes:
  mongodb_database:

networks:
  fetch-posts-network:
    driver: bridge
