# Stage 1: Build the application
FROM node:16.13.1-alpine3.12 AS build
WORKDIR /src/app

COPY package*.json ./
RUN npm ci --only=production

COPY . .
RUN npm run build

# Stage 2: Create a production-ready image
FROM node:16.13.1-alpine3.12 AS production
WORKDIR /src/app

COPY package*.json ./
RUN npm ci --only=production

COPY --from=build /src/app/dist ./dist

ENV NODE_ENV=production

EXPOSE ${NODE_CONTAINER_PORT}

